# config.yaml

seed: 1234  # Random seed for reproducibility

# Model configuration. Choose one of:
#   - "MGModule"
#   - "MGModule_SingleHead"
#   - "MGModuleViT"
#   - "MGModule_SingleHead_Mamm_Only"
model_class_name: "MGModule_four_view_meta_avg_cross_attention"
# Optionally, specify a pretrained model path (use null if not used)
pretrained_path: /beacon-scratch/tuxunlu/git/tdlu/mgh_mammo_MIRAI_Base_May20_2019.p
use_compile: True  # Use TorchScript compilation for faster inference
freeze_backbone: False  # Freeze the backbone model during training

# Loss configuration. The current options are:
#   - "cross_entropy"
#   - "hierarchical_cross_entropy"
loss: [FocalLoss]  
loss_weight: [1.0]  # Weight for the loss function
# weight_decay: 1.0e-3
# label_smoothing: 0.15
# use_ohem: False  # Use Online Hard Example Mining
# keep_ratio: 0.7  # Ratio of hard examples to keep
weight_decay: 1.0e-3
# focal_loss_alpha: [0.7507598784194529, 0.8045602605863192, 2.3523809523809525]  # Focal loss alpha values for each class
focal_loss_alpha: [0.6627906976744186, 2.0357142857142856]
focal_loss_gamma:  2  # Focal loss gamma value

# Training configuration.
enable_checkpointing: True  # Enable model checkpointing
lr: 5.0e-3
max_epochs: 1000
lr_scheduler: "cyclic"
lr_decay_epochs: 100
lr_decay_min_lr: 5.0e-6

# Hyperparameters configuration.
# Note: Some of these values (e.g., target, description, num_bins, batch_size)
# are overwritten later in the script; adjust these here if desired.
dataset_name: "TDLUDataset_torchio_four_view_meta_avg_folds"
meta_cols: ['BreastDensity_avg_four', 'mamm_age', 'cbmi_donation', 'geanc_Race']
cross_val_fold: 0
mamm_only: True
batch_size: 24
test_batch_size: 1
num_save: 20
num_bins: 2
target: "tdlu_density_extreme"            # Target label name.
zero: False
label: True
run_dir: "./runs"                 # Base directory to save run outputs.
num_workers: 12
persistent_workers: False
pin_memory: False
# Image directory for the training data.
image_dir: "/beacon-scratch/tuxunlu/git/tdlu/dataset/WUSTL_png_nomarker_16"
# CSV file containing annotations.
csv_path: "/beacon-scratch/tuxunlu/git/tdlu/dataset/umd_annot_md_TDLU_y2025m07d09.csv"
augment: True
weights_json_path: null           # Optional weights JSON path (if applicable)
device: "cuda"                    # Use "cuda" if a GPU is available, otherwise "cpu"

# Logging configuration.
log_dir: "/beacon-scratch/tuxunlu/git/tdlu/runs"
experiment_name: "config_torchio_2bins_tdlu_four_views_fold_0_focalloss_gamma2_randomapply_meta_extreme_avg_cross_attention_randomapply_0.3_0.5"
log_every_n_steps: 1  # Log every n steps