# config.yaml

seed: 1234  # Random seed for reproducibility

# Model configuration. Choose one of:
#   - "MGModule"
#   - "MGModule_SingleHead"
#   - "MGModuleViT"
#   - "MGModule_SingleHead_Mamm_Only"
model_interface: "ModelInterface"
model_class_name: "MGModule_four_view_avg_cross_attention"
# Optionally, specify a pretrained model path (use null if not used)
pretrained_path: /beacon-scratch/tuxunlu/git/tdlu/mgh_mammo_MIRAI_Base_May20_2019.p
use_compile: True  # Use TorchScript compilation for faster inference
freeze_backbone: False  # Freeze the backbone model during training
num_meta_features: 0  # Not used for image-only model (model ignores metadata even if dataset returns it)
resume_from_manual_checkpoint: null
fusion_method: "self_attention"  # Options: "self_attention", "concat", "weighted_sum"

# Loss configuration. The current options are:
#   - "cross_entropy"
#   - "hierarchical_cross_entropy"
loss: [FocalLoss]  
loss_weight: [1]  # Weight for the loss function
weight_decay: 1.0e-5
# label_smoothing: 0.15
# use_ohem: False  # Use Online Hard Example Mining
# keep_ratio: 0.7  # Ratio of hard examples to keep
focal_loss_alpha: [0.7507598784194529, 0.8045602605863192, 2.3523809523809525]  # Focal loss alpha values for each class
focal_loss_gamma:  0  # Focal loss gamma value

# Training configuration.
enable_checkpointing: True  # Enable model checkpointing
max_epochs: 500
lr: 5.0e-04
lr_decay_epochs: 500
lr_decay_min_lr: 1.0e-06
lr_scheduler: "cosine"

# Hyperparameters configuratison.
# Note: Some of these values (e.g., target, description, num_bins, batch_size)
# are overwritten later in the script; adjust these here if desired.
dataset_name: "TDLUDataset_torchio_four_view_mask_meta_avg_10_folds_Hologic"
meta_cols: ['BreastDensity_avg', 'mamm_age', 'cbmi_donation', 'geanc_Race']  # Dataset expects these for compatibility, but model ignores metadata
cross_val_fold: 9
mamm_only: True
batch_size: 12
test_batch_size: 1 
num_save: 50
num_bins: 3
target: "tdlu_density_extreme_zero"            # Target label name.
label_type: "label"
run_dir: "./runs"                 # Base directory to save run outputs.
num_workers: 6
persistent_workers: False
pin_memory: False
# Image directory for the training data.
image_dir: "/beacon-scratch/tuxunlu/git/tdlu/KOMEN/WUSTL_png_nomarker_16"
dense_mask_dir: "/beacon-scratch/tuxunlu/git/tdlu/KOMEN/LIBRA_Masks_npy"
breast_mask_dir: "/beacon-scratch/tuxunlu/git/tdlu/KOMEN/WUSTL_png_nomarker_16_contour"
# CSV file containing annotations.
csv_path: "/beacon-scratch/tuxunlu/git/tdlu/KOMEN/umd_annot_md_TDLU_y2025m07d09.csv"
use_augmentation: True
weights_json_path: null           # Optional weights JSON path (if applicable)
device: "cuda"                    # Use "cuda" if a GPU is available, otherwise "cpu"

# Logging configuration.
log_dir: "/beacon-scratch/tuxunlu/git/tdlu/runs"
experiment_name: "config_torchio_3bins_tdlu_extreme_zero_stacked_10fold_9_focalloss_gamma0_avg_cross_attention_resnet_norm_hologic_image_only"
log_every_n_steps: 1  # Log every n steps
