# config.yaml

seed: 42  # Random seed for reproducibility

# Model configuration. Choose one of:
#   - "MGModule"
#   - "MGModule_SingleHead"
#   - "MGModuleViT"
#   - "MGModule_SingleHead_Mamm_Only"
model_class_name: "MGModule_four_view"
# Optionally, specify a pretrained model path (use null if not used)
pretrained_path: /fs/nexus-scratch/tuxunlu/git/tdlu/mgh_mammo_MIRAI_Base_May20_2019.p
use_compile: True  # Use TorchScript compilation for faster inference
freeze_backbone: False  # Freeze the backbone model during training

# Loss configuration. The current options are:
#   - "cross_entropy"
#   - "hierarchical_cross_entropy"
loss: [CrossEntropyLoss]
loss_weight: [0.5]  # Weight for the loss function
weight_decay: 1.0e-3
label_smoothing: 0.15
use_ohem: True  # Use Online Hard Example Mining
keep_ratio: 0.7  # Ratio of hard examples to keep

# Training configuration.
enable_checkpointing: True  # Enable model checkpointing
lr: 1.0e-4
max_epochs: 500
lr_scheduler: "cyclic"
lr_decay_epochs: 100
lr_decay_min_lr: 5.0e-6

# Hyperparameters configuration.
# Note: Some of these values (e.g., target, description, num_bins, batch_size)
# are overwritten later in the script; adjust these here if desired.
dataset_name: "TDLUDataset_torchio_four_view"
mamm_only: True
batch_size: 12
test_batch_size: 1
num_save: 20
num_bins: 2
target: "tdlu_density"            # Target label name.
run_dir: "./runs"                 # Base directory to save run outputs.
num_workers: 12
persistent_workers: False
pin_memory: True
# Image directory for the training data.
image_dir: "/fs/nexus-scratch/tuxunlu/git/tdlu/dataset/WUSTL_png_nomarker_16"
# CSV file containing annotations.
csv_path: "/fs/nexus-scratch/tuxunlu/git/tdlu/dataset/umd_annot_md_TDLU_y2025m04d28.csv"
augment: True
weights_json_path: null           # Optional weights JSON path (if applicable)
device: "cuda"                    # Use "cuda" if a GPU is available, otherwise "cpu"

# Logging configuration.
log_dir: "/fs/nexus-scratch/tuxunlu/git/tdlu/runs"
experiment_name: "config_torchio_2bins_tdlu_four_views_ohem_mixed"
log_every_n_steps: 1  # Log every n steps